_core:
  default_config_hash: KWr7SpVQsREFRiMBtX1Pzm_rPtvgA7Q1BG536zXlLoM
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
current_theme: none
facebook_url: ''
twitter_url: ''
pinterest_url: ''
google_plus_url: ''
linkedin_url: 'https://www.linkedin.com/in/oscar-portillo-herrera-5a4a611a6/'
instagram_url: 'https://www.instagram.com/oscarportillosv/'
youtube_url: ''
drupal_url: ''
rss_url: ''
copyright_text: 'Copyright 2022 - All Rights Reserved'
show_social_icon: 1
show_credit_link: 1
top_region: 1
main_region: 1
bottom_region: 1
footer_region: 1
full_opacity_onscroll: 1
border_animation: 1
langcode: es
logo:
  use_default: 0
  path: 'public://logo_0.jpg'
favicon:
  use_default: 1
website_width: none
equal_width: 0
layout_user_login_custom: 0
sitename_animation: none
pagetitle_animation: none
d8w3css_font_awesome_4: 0
d8w3css_google_font_local: 0
d8w3css_site_gf: none
d8w3css_site_gfh: none
d8w3css_site_gfs: none
color_page_wrapper: w3-blue
color_header: 'w3-link-white w3-link-orange-hover'
color_primary_menu: ''
color_welcome_text: ''
color_highlighted: ''
color_top_container: ''
color_top_first: ''
color_top_second: ''
color_top_third: ''
color_page_title: ''
color_main: ''
color_breadcrumb: ''
color_sidebar_first: ''
color_content: ''
color_sidebar_second: ''
color_bottom_container: ''
color_bottom_first: ''
color_bottom_second: ''
color_bottom_third: ''
color_bottom_forth: ''
color_footer_container: ''
color_footer_first: ''
color_footer_second: ''
color_footer_third: ''
color_footer_menu: ''
color_copyright: ''
